import { useEffect, useMemo, useState } from 'react';
import type { TodoItem } from '../core/contracts/domain';
import { beginGoogleCalendarConnection, disconnectGoogleCalendar, getCalendarStatus, reconcileCalendar, removeCalendarBlock, scheduleCalendarBlock, type CalendarStatus } from '../infrastructure/calendar/calendarScheduling';

const localDateTime = (value?: string | null) => {
  const date = value ? new Date(value) : new Date(Date.now() + 30 * 60_000);
  date.setMinutes(Math.ceil(date.getMinutes() / 15) * 15, 0, 0);
  const offset = date.getTimezoneOffset() * 60_000;
  return new Date(date.getTime() - offset).toISOString().slice(0, 16);
};
const messageFor = (error: unknown) => {
  const code = error instanceof Error ? error.message : '';
  if (code === 'reauthorization_required') return 'Google needs permission again. Reconnect your calendar to continue.';
  if (code === 'connection_unavailable') return 'This calendar connection is no longer available. Reconnect and try again.';
  if (code === 'calendar_change_requires_removal') return 'Remove the existing block before moving this task to another calendar. This prevents duplicate events.';
  if (code === 'disabled') return 'Calendar scheduling is not enabled for this environment.';
  return 'We could not confirm that calendar block. Your task has not been changed.';
};

export function CalendarScheduleControl({ task, scheduledStartAt, estimateMinutes, existingBlock, onScheduled }: { task: TodoItem; scheduledStartAt?: string | null; estimateMinutes?: number | null; existingBlock?: { calendar_id: string; starts_at: string; duration_minutes: number; external_event_url?: string | null; sync_state?: string; last_reconciled_at?: string | null } | null; onScheduled?: () => void }) {
  const [status, setStatus] = useState<CalendarStatus | null>(null);
  const [startsAt, setStartsAt] = useState(() => localDateTime(scheduledStartAt));
  const [duration, setDuration] = useState(estimateMinutes && estimateMinutes >= 5 ? estimateMinutes : 30);
  const [calendarId, setCalendarId] = useState('primary'); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  const selectedCalendar = useMemo(() => status?.calendars?.find((calendar) => calendar.id === calendarId), [calendarId, status]);
  const load = () => void getCalendarStatus().then((next) => { const calendars = next.calendars ?? []; setStatus(next); setCalendarId((current) => calendars.some((calendar) => calendar.id === current) ? current : next.defaultCalendarId ?? calendars.find((calendar) => calendar.primary)?.id ?? 'primary'); }).catch(() => setStatus({ status: 'unavailable' }));
  useEffect(load, []);
  useEffect(() => { if (scheduledStartAt) setStartsAt(localDateTime(scheduledStartAt)); }, [scheduledStartAt]);
  const connect = async () => { setBusy(true); setNotice(''); try { await beginGoogleCalendarConnection(); } catch (error) { setNotice(messageFor(error)); setBusy(false); } };
  const schedule = async () => { if (!status?.connectionId) return; setBusy(true); setNotice(''); try { const result = await scheduleCalendarBlock({ taskId: task.id, connectionId: status.connectionId, calendarId, startsAt: new Date(startsAt).toISOString(), durationMinutes: duration }); setNotice(result.eventUrl ? 'Calendar block confirmed. You can open it in Google Calendar.' : 'Calendar block confirmed.'); onScheduled?.(); } catch (error) { setNotice(messageFor(error)); } finally { setBusy(false); } };
  const remove = async () => { if (!status?.connectionId) return; setBusy(true); setNotice(''); try { await removeCalendarBlock(task.id, status.connectionId); setNotice('Calendar block removed. Your task remains in Task-Laureate.'); onScheduled?.(); } catch (error) { setNotice(messageFor(error)); } finally { setBusy(false); } };
  const sync = async () => { if (!status?.connectionId || !existingBlock) return; setBusy(true); setNotice(''); try { await reconcileCalendar(status.connectionId, existingBlock.calendar_id); setNotice('Calendar checked. Any time changes are now reflected in this task.'); onScheduled?.(); } catch (error) { setNotice(messageFor(error)); } finally { setBusy(false); } };
  const disconnect = async () => { setBusy(true); setNotice(''); try { await disconnectGoogleCalendar(); setStatus({ status: 'disconnected' }); setNotice('Google Calendar disconnected. Existing calendar events were left untouched.'); onScheduled?.(); } catch (error) { setNotice(messageFor(error)); } finally { setBusy(false); } };
  if (!status) return <section className="calendar-schedule-control" aria-busy="true"><p>Checking calendar connection…</p></section>;
  if (status.status === 'unavailable') return <section className="calendar-schedule-control calendar-schedule-control--unavailable"><div><p className="calendar-schedule-control__eyebrow">Calendar</p><h3>Put focused work on your calendar</h3><p>One-way scheduling is not enabled in this environment. Your task stays private and unchanged.</p></div></section>;
  if (status.status !== 'connected') return <section className="calendar-schedule-control"><div><p className="calendar-schedule-control__eyebrow">Calendar</p><h3>Give this task a protected time</h3><p>Connect Google Calendar once. Task-Laureate will only create or update blocks you explicitly schedule—never import or alter your existing events.</p></div><button className="primary-button" type="button" disabled={busy} onClick={() => void connect()}>{busy ? 'Opening Google…' : status.status === 'reauthorization_required' ? 'Reconnect Google Calendar' : 'Connect Google Calendar'}</button>{notice ? <p role="status">{notice}</p> : null}</section>;
  return <section className="calendar-schedule-control" aria-labelledby={`calendar-schedule-${task.id}`}><div><p className="calendar-schedule-control__eyebrow">Calendar block</p><h3 id={`calendar-schedule-${task.id}`}>{existingBlock ? 'This task has protected time' : 'Choose a time you can protect'}</h3><p>{existingBlock?.sync_state === 'removed_external' ? 'This block was removed in Google Calendar. The task is safe; choose a new time whenever you are ready.' : existingBlock ? 'Changes made to this Task-Laureate block in Google Calendar automatically update this task’s scheduled time. We never import or alter ordinary calendar events.' : 'A block is created only after Google Calendar confirms it. You can update or remove it here anytime.'}</p></div><div className="calendar-schedule-control__form"><label className="field"><span>Start</span><input type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} disabled={busy} /></label><label className="field"><span>Duration</span><select value={duration} onChange={(event) => setDuration(Number(event.target.value))} disabled={busy}>{[5, 10, 15, 30, 45, 60, 90, 120].map((minutes) => <option key={minutes} value={minutes}>{minutes < 60 ? `${minutes} minutes` : `${minutes / 60} hour${minutes === 60 ? '' : 's'}`}</option>)}</select></label><label className="field"><span>Calendar</span><select value={calendarId} onChange={(event) => setCalendarId(event.target.value)} disabled={busy || !!existingBlock}>{status.calendars?.map((calendar) => <option key={calendar.id} value={calendar.id}>{calendar.summary}{calendar.primary ? ' · Primary' : ''}</option>)}</select>{existingBlock ? <small>Remove this block before choosing a different calendar.</small> : null}</label></div><div className="calendar-schedule-control__actions"><button className="primary-button" type="button" disabled={busy || !startsAt || !selectedCalendar} onClick={() => void schedule()}>{busy ? 'Confirming…' : existingBlock ? 'Update calendar block' : 'Add to calendar'}</button>{existingBlock ? <button className="secondary-button" type="button" disabled={busy} onClick={() => void sync()}>Check calendar now</button> : null}{existingBlock ? <button className="secondary-button" type="button" disabled={busy} onClick={() => void remove()}>Remove block</button> : null}{existingBlock?.external_event_url ? <a className="secondary-button" href={existingBlock.external_event_url} target="_blank" rel="noreferrer">Open in Google Calendar</a> : null}<button className="calendar-schedule-control__disconnect" type="button" disabled={busy} onClick={() => void disconnect()}>Disconnect Google Calendar</button></div>{notice ? <p className="calendar-schedule-control__notice" role="status">{notice}</p> : null}</section>;
}
