import { useEffect, useState } from 'react';
import { getNotificationEvents, getNotificationPreferences, markNotificationRead, saveNotificationPreferences, type NotificationEvent, type NotificationPreferences } from '../infrastructure/notifications/inbox';

/** Read-only user inbox for messages generated by the daily Vercel cron job. */
export function NotificationInbox() {
  const [events, setEvents] = useState<NotificationEvent[]>([]);
  const [preferences, setPreferences] = useState<NotificationPreferences>({ due_soon: true, weekly_digest: false });
  const [message, setMessage] = useState('');

  useEffect(() => {
    void Promise.all([getNotificationEvents(), getNotificationPreferences()])
      .then(([loadedEvents, savedPreferences]) => {
        setEvents(loadedEvents);
        if (savedPreferences) setPreferences(savedPreferences);
      })
      .catch(() => setMessage('Your notification inbox could not be loaded.'));
  }, []);

  const markRead = async (event: NotificationEvent) => {
    try {
      await markNotificationRead(event.id);
      setEvents((current) => current.map((item) => item.id === event.id ? { ...item, read_at: new Date().toISOString() } : item));
    } catch { setMessage('We could not update that notification.'); }
  };

  const savePreference = async (name: keyof NotificationPreferences, value: boolean) => {
    const next = { ...preferences, [name]: value };
    setPreferences(next);
    setMessage('');
    try {
      await saveNotificationPreferences(next);
    } catch {
      setPreferences(preferences);
      setMessage('We could not save that notification preference.');
    }
  };

  return <section className="notification-inbox" aria-labelledby="notification-inbox-title">
    <div><p className="notification-inbox__eyebrow">In-app notifications</p><h2 id="notification-inbox-title">Your inbox</h2><p>Private reminders created by a daily check. They appear here; this app does not claim to send email or push alerts.</p></div>
    <fieldset className="notification-inbox__preferences">
      <legend>What should appear in your inbox?</legend>
      <label><input type="checkbox" checked={preferences.due_soon} onChange={(event) => void savePreference('due_soon', event.target.checked)} /> <span><strong>Due soon</strong><small>Tasks due today or tomorrow (UTC).</small></span></label>
      <label><input type="checkbox" checked={preferences.weekly_digest} onChange={(event) => void savePreference('weekly_digest', event.target.checked)} /> <span><strong>Weekly digest</strong><small>A Sunday (UTC) summary of your active work.</small></span></label>
    </fieldset>
    <p className="notification-inbox__timing">Daily checks run on Vercel Hobby. Delivery time may vary within the scheduled UTC hour.</p>
    {events.length === 0 && !message ? <p className="notification-inbox__empty">Nothing needs your attention right now.</p> : null}
    <div className="notification-inbox__items">{events.map((event) => <article key={event.id} className={event.read_at ? 'is-read' : ''}><div><strong>{event.title}</strong><p>{event.body}</p><small>{new Date(event.created_at).toLocaleString()}</small></div>{!event.read_at ? <button type="button" onClick={() => void markRead(event)}>Mark read</button> : null}</article>)}</div>
    {message ? <p role="status">{message}</p> : null}
  </section>;
}
