import { useEffect, useState } from 'react';
import { getTaskReminderSetup, saveTaskReminder, setTaskAssignee, type TaskReminderConfiguration } from '../infrastructure/notifications/taskReminders';

type Candidate = { user_id: string; access_role: string };
const shortId = (value: string) => `${value.slice(0, 8)}…${value.slice(-4)}`;

/** Owner-only control, intentionally separate from the task editor. */
export function TaskReminderControl({ taskId }: { taskId: string }) {
  const [candidates, setCandidates] = useState<Candidate[]>([]); const [assigned, setAssigned] = useState<Set<string>>(new Set());
  const [rule, setRule] = useState<TaskReminderConfiguration>({ enabled: false, offset_minutes: 1440, channels: ['in_app'] });
  const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { let active = true; void getTaskReminderSetup(taskId).then((setup) => { if (active) { setCandidates(setup.candidates); setAssigned(setup.assigned); setRule(setup.rule); } }).catch(() => { if (active) setMessage('Reminder controls are available only to the task owner.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [taskId]);
  const updateAssignee = async (userId: string, value: boolean) => { setSaving(true); setMessage(''); try { await setTaskAssignee(taskId, userId, value); setAssigned((current) => { const next = new Set(current); value ? next.add(userId) : next.delete(userId); return next; }); } catch { setMessage('We could not update this assignee.'); } finally { setSaving(false); } };
  const saveRule = async (next: TaskReminderConfiguration) => { setSaving(true); setMessage(''); try { await saveTaskReminder(taskId, next); setRule(next); setMessage(next.enabled ? 'Reminder schedule saved.' : 'Reminder paused.'); } catch { setMessage('We could not save this reminder schedule.'); } finally { setSaving(false); } };
  if (loading) return <section className="task-reminder-control" aria-busy="true"><h3>Reminders</h3><p>Loading reminder settings…</p></section>;
  if (!candidates.length) return null;
  return <section className="task-reminder-control" aria-labelledby={`task-reminders-${taskId}`}><div><h3 id={`task-reminders-${taskId}`}>Assignment & reminders</h3><p>Only people who already have access can be assigned. They choose their own delivery channels; reminders are processed by the daily delivery check.</p></div><div className="task-reminder-control__people">{candidates.map((candidate) => <label key={candidate.user_id}><input type="checkbox" checked={assigned.has(candidate.user_id)} disabled={saving} onChange={(event) => void updateAssignee(candidate.user_id, event.target.checked)} /><span><strong>{candidate.access_role === 'owner' ? 'List owner' : `Collaborator · ${shortId(candidate.user_id)}`}</strong><small>{candidate.access_role === 'viewer' ? 'Read-only access' : 'Can update tasks'}</small></span></label>)}</div><div className="task-reminder-control__schedule"><label><input type="checkbox" checked={rule.enabled} disabled={saving || !assigned.size} onChange={(event) => void saveRule({ ...rule, enabled: event.target.checked })} /> Remind assignees</label><select aria-label="Reminder timing" disabled={saving || !rule.enabled} value={rule.offset_minutes} onChange={(event) => void saveRule({ ...rule, offset_minutes: Number(event.target.value) })}><option value={1440}>1 day before due date</option><option value={4320}>3 days before due date</option><option value={10080}>1 week before due date</option></select></div>{!assigned.size ? <p className="task-reminder-control__hint">Assign at least one collaborator before enabling a reminder.</p> : null}{message ? <p className="task-reminder-control__hint" role="status">{message}</p> : null}</section>;
}
